spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb  # PostgreSQL 데이터베이스 URL
    username: postgre_user                                 # PostgreSQL 사용자명
    password: postgre_password                             # PostgreSQL 비밀번호
    driver-class-name: org.postgresql.Driver
    
  jpa:
      hibernate:
        ddl-auto: update  # 개발 중에는 update 사용, 운영에서는 validate 또는 none 권장
      show-sql: true      # 쿼리 출력 여부
      properties:
        hibernate:
          format_sql: true  # SQL 포맷팅을 적용해 읽기 쉽게 표시
